apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service-deployment
  labels:
    app: auth-service
spec:
  replicas: 2  # Example number of replicas
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-service
        image: docker.io/onwardfave/auth-service:v0.1  # Use your local image tag
        imagePullPolicy: Always  # Use the local image if available
        ports:
        - containerPort: 3001
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: ecommerce-config  # Name of your ConfigMap
              key: DB_HOST
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: ecommerce-secret  # Name of your Secret
              key: DB_USER
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: ecommerce-secret  # Name of your Secret
              key: DB_PASS
        - name: AUTH_DB_NAME
          valueFrom:
            configMapKeyRef:
              name: ecommerce-config  # Name of your ConfigMap
              key: AUTH_DB_NAME
        resources:
          requests:
            cpu: "100m"
            memory: "200Mi"
          limits:
            cpu: "200m"
            memory: "400Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth-service
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 3001  # Changed to the new port
  type: ClusterIP
