apiVersion: v1
kind: Secret
metadata:
  name: ecommerce-secret
type: Opaque
data:
  DB_USER: cm9vdA== # create and put base64 encoded 'root'
  DB_PASS: cGFzc3dvcmQ= # create and put base64 encoded 'password'
  MYSQL_ROOT_PASSWORD: cGFzc3dvcmQ= #base64 encoded 'password'
  JWT_SECRET: encodeyourjwtsecretandputithere # base64 encoded JWT secret