apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service-deployment
  labels:
    app: order-service
spec:
  replicas: 2 # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - name: order-service
        image: docker.io/onwardfave/order-service:v0.3  # Use your local image tag
        imagePullPolicy: Always  # Use the local image if available
        resources:
          requests:
            cpu: "250m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        ports:
        - containerPort: 3003
        env:
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                name: ecommerce-config  # Name of your ConfigMap
                key: DB_HOST
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: ecommerce-secret  # Name of your Secret
                key: DB_USER
          - name: DB_PASS
            valueFrom:
              secretKeyRef:
                name: ecommerce-secret  # Name of your Secret
                key: DB_PASS
          - name: ORDERS_DB_NAME
            valueFrom:
              configMapKeyRef:
                name: ecommerce-config  # Name of your ConfigMap
                key: ORDERS_DB_NAME
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  selector:
    app: order-service
  ports:
  - protocol: TCP
    port: 3003
    targetPort: 3003
  type: ClusterIP
