apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service-deployment
  labels:
    app: product-service
spec:
  replicas: 2 # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
      - name: product-service
        image: docker.io/onwardfave/product-service:v0.1  # Use your local image tag
        imagePullPolicy: Always  # Use the local image if available
        resources:
          requests:
            cpu: "250m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        ports:
        - containerPort: 3000
        env:
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                name: ecommerce-config  # Name of your ConfigMap
                key: DB_HOST
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: ecommerce-secret  # Name of your Secret
                key: DB_USER
          - name: DB_PASS
            valueFrom:
              secretKeyRef:
                name: ecommerce-secret  # Name of your Secret
                key: DB_PASS
          - name: PRODUCTS_DB_NAME
            valueFrom:
              configMapKeyRef:
                name: ecommerce-config  # Name of your ConfigMap
                key: PRODUCTS_DB_NAME
---
apiVersion: v1
kind: Service
metadata:
  name: product-service
spec:
  selector:
    app: product-service
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: ClusterIP
